### ISSUE TITLE
Network Contributor Does not apply Correctly

### ISSUE THREAD

**Issue by b-odonoghue** [Azure-Terraform/terraform-azurerm-kubernetes#23]
Hey I am trying to use the private subnet to allow services to get private IPs assigned to them. And currently that does not seem to be working as expected. 

My TF call looks like this 
```
data "azurerm_subnet" "devops" {
  name                 = "snet-devops-dev-eastus"
  virtual_network_name = "vnet-tmx-dev-eastus"
  resource_group_name  = "rg-network-dev-eastus"
}

module "aks" {
  source = "github.com/Azure-Terraform/terraform-azurerm-kubernetes.git?ref=v1.6.0"

  resource_group_name          = "rg-devops-dev-eastus"
  aks_managed_vnet             = false
  configure_subnet_nsg_rules   = false
  default_node_pool_node_count = 2
  default_node_pool_subnet     = "snet-devops-dev-eastus"
  kubernetes_version           = "1.18.14"
  location                     = "eastus"
  names                        = {
    resource_group_type = "app"
    product_name        = "tmx"
    environment         = "dev"
    location            = "eastus"
  }
  node_pool_subnets = {
    snet-devops-dev-eastus = {
      id                  = data.azurerm_subnet.devops.id
      resource_group_name = "rg-network-dev-eastus"
      security_group_name = data.azurerm_subnet.devops.network_security_group_id
    }
  }
  tags = {
    cost_center = "tx501"
    owner       = "devops"
    purpose     = "aks-testing"
  }
}
```
I understand the way I am doing tags and names is not the ideal way, and the metadata module is the correct way to go but this is simply to make sure it works as expected before a real rollout.

I have the configure_sp_subnet_role left default, which is true, meaning I am running only this section below from the subnet submodule

And in my plans I do see this Network Contributor role being created, but when I try to edit a service with the desired annotations it just hangs and throws the following error.

Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client '988f0f1c-7bdf-476d-963c-0427eaea4cbc' with object id '988f0f1c-7bdf-476d-963c-0427eaea4cbc' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/f6611492-8d20-4c64-af88-b10a2d37a0f5/resourceGroups/rg-network-dev-eastus/providers/Microsoft.Network/virtualNetworks/vnet-tmx-dev-eastus/subnets/snet-devops-dev-eastus' or the scope is invalid. If access was recently granted, please refresh your credentials."}}

even after waiting 20 minutes I am still seeing the error above and the service in a pending state.
```
ingress-nginx   nginx-ingress-nginx-controller             LoadBalancer   10.0.120.48    <pending>     80:30242/TCP,443:31991/TCP   24m
```

I think we should be passing `azurerm_kubernetes_cluster.aks-dev-cluster.identity[0].principal_id` to the subnet submoudle for `var.principal_id` instead of `azurerm_kubernetes_cluster.aks.kubelet_identity.0.object_id`

I manually made this change after cloning the repo. After about 10 minutes I was able to get an IP assigned 
```
ingress-nginx   nginx-ingress-nginx-controller             LoadBalancer   10.0.161.156   10.226.12.71   80:32186/TCP,443:32280/TCP   9m1s
```

I opened this pr https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/24 to better describe the change I am thinking.

I am unsure if there is some technical reason that we should be using kubelet_identity and not cluster identity?

**Comment by b-odonoghue** [comment]
@dutsmiller  @hiscjo01 apologies if there is already some kind of notification automatically sent for issues, but is there something that I should be looking for outside this module?

**Comment by dutsmiller** [comment]
Merged https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/24

good catch!
