### ISSUE TITLE
Error: creating Managed Kubernetes Cluster "aks-app-terraform-sandbox-eastus2" 

### ISSUE THREAD

**Issue by loisra01** [Azure-Terraform/terraform-azurerm-kubernetes#26]
Trying to use this module to create a aks cluster in the sandbox env and I got the error bellow. Can someone help pass this.

Error: creating Managed Kubernetes Cluster "aks-app-terraform-sandbox-eastus2" (Resource Group "app-terraform-sandbox-eastus2"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PreconditionFailed" Message="Provisioning of resource(s) for container service aks-app-terraform-sandbox-eastus2 in resource group app-terraform-sandbox-eastus2 failed. Message: The template deployment failed with multiple errors. Please see details for more information.. Details: [{\"code\":\"RequestDisallowedByPolicy\",\"message\":\"Resource 'aks-vnet-13849498' was disallowed by policy. Policy identifiers: '[{\\\"policyAssignment\\\":{\\\"name\\\":\\\"Sandbox Restrictions - No Public Interfaces\\\",\\\"id\\\":\\\"/subscriptions/c92ae950-1217-4834-821c-261d2f463e17/providers/Microsoft.Authorization/policyAssignments/custom-sandbox-policy\\\"},\\\"policyDefinition\\\":{\\\"name\\\":\\\"Sandbox Restrictions\\\",\\\"id\\\":\\\"/subscriptions/c92ae950-1217-4834-821c-261d2f463e17/providers/Microsoft.Authorization/policyDefinitions/custom-sandbox-policy\\\"}}]'.\",\"target\":\"aks-vnet-13849498\"},{\"code\":\"RequestDisallowedByPolicy\",\"message\":\"Resource 'aks-agentpool-13849498-routetable' was disallowed by policy. Policy identifiers: '[{\\\"policyAssignment\\\":{\\\"name\\\":\\\"Sandbox Restrictions - No Public Interfaces\\\",\\\"id\\\":\\\"/subscriptions/c92ae950-1217-4834-821c-261d2f463e17/providers/Microsoft.Authorization/policyAssignments/custom-sandbox-policy\\\"},\\\"policyDefinition\\\":{\\\"name\\\":\\\"Sandbox Restrictions\\\",\\\"id\\\":\\\"/subscriptions/c92ae950-1217-4834-821c-261d2f463e17/providers/Microsoft.Authorization/policyDefinitions/custom-sandbox-policy\\\"}}]'.\",\"target\":\"aks-agentpool-13849498-routetable\"}]"

  on .terraform\modules\kubernetes\main.tf line 5, in resource "azurerm_kubernetes_cluster" "aks":
   5: resource "azurerm_kubernetes_cluster" "aks" {

**Comment by dutsmiller** [comment]
This is related to an infosec policy being applied to sandbox environments.  Using an environment which allows public IP allocation is required.
