### ISSUE TITLE
Validate AKS secondary resource group length

### ISSUE THREAD

**Issue by jamurtag** [Azure-Terraform/terraform-azurerm-kubernetes#33]
Using the code within the mixed-arch example I encoutered an error:

```bash
module.kubernetes.azurerm_kubernetes_cluster.aks: Creating...

Error: creating Managed Kubernetes Cluster "aks-app-tucdlvurpmwf-sandbox-westeurope" (Resource Group "app-tucdlvurpmwf-sandbox-westeurope"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The length of the node resource group name is too long. The maximum length is 80 and the length of the value provided is 89. Please see https://aka.ms/aks-naming-rules for more details." Target="name"

  on .terraform/modules/kubernetes/main.tf line 41, in resource "azurerm_kubernetes_cluster" "aks":
  41: resource "azurerm_kubernetes_cluster" "aks" {
```

The [secondary resource group name](https://docs.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks) is formed as follows - `MC_myResourceGroup_myAKSCluster_region`, so in this case the generated name was `MC_app-tucdlvurpmwf-sandbox-westeurope_aks-app-tucdlvurpmwf-sandbox-westeurope_westeurope`, exceeding the 80 character resource group limit.

This module should verify this name limit, providing an error during the plan phase. Also, we need to take into account how upstream modules (i.e. metadata) set values which will be concatenated later.

If a region is preferred in each resource, the module could strip out the duplicates from the generated name, then [pass a custom resource group name](https://docs.microsoft.com/en-us/azure/aks/faq#can-i-provide-my-own-name-for-the-aks-node-resource-group) option (however this is a preview feature).

**Comment by dutsmiller** [comment]
I've added a check for this in https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/31
