### ISSUE TITLE
Azure AD integration must be enabled

### ISSUE THREAD

**Issue by jamurtag** [Azure-Terraform/terraform-azurerm-kubernetes#34]
Azure AD integration is mandatory for user API access.

This is implemented via the azure_active_directory resource block in Terraform. Managed should be set to true so Azure will manage Service Principal rotation (requires testing in Terraform).

This also supports AzureRM RBAC as an extra authorization layer - however whether we implement this is still TBD.

**Comment by dutsmiller** [comment]
Added in https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/36
