### ISSUE TITLE
Role assignments should use Principal Id 

### ISSUE THREAD

**Issue by appkins** [Azure-Terraform/terraform-azurerm-kubernetes#46]
https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/bfe925b1c7d918a27c375651b5000c09ec8b076d/main.tf#L14

This should instead reference the principal_id property:

`principal_id         = (var.user_assigned_identity == null ? azurerm_user_assigned_identity.aks.0.principal_id :
                          var.user_assigned_identity.principal_id)`

**Comment by jhisc** [comment]
Hi @appkins  - Can you review that PR please and let me know if it fixes the issue?
Thanks

**Comment by appkins** [comment]
@jhisc We actually need this changed in one other location. I saw the pull request was approved before I could catch these

https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/1f61f8ce8d2373a9c720ac5f79d70316d37c9e7b/main.tf#L24

This needs to reference the principal_id. I also found that there's an incorrect reference in the output here:

https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/9966c3653cd67e2b8c149343c87d945d3aa6303e/output.tf#L76

**Comment by appkins** [comment]
This issue is fixed. Thanks @jhisc!
