### ISSUE TITLE
Remove NSG rule code

### ISSUE THREAD

**Issue by jamurtag** [Azure-Terraform/terraform-azurerm-kubernetes#53]
This module is used to create and manage a single AKS cluster.

As NSG rules implemented here are not specific to a cluster, they should be moved to a vnet module (either as a Kubernetes flag in a generic module or to an opinionated AKS vnet module).

This supports the multiple clusters per subnet use case with a single dependency and less complexity.

**Comment by dutsmiller** [comment]
https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/43
