### ISSUE TITLE
Control plane user assigned identity name

### ISSUE THREAD

**Issue by jamurtag** [Azure-Terraform/terraform-azurerm-kubernetes#68]
The control plane user assigned identity name is set to "uai-${local.cluster_name}".

Either support overriding this, or set to a more descriptive value.

* The default value should probably be "${local.cluster_name}-control-plane" (see [docs](https://docs.microsoft.com/en-us/azure/aks/use-managed-identity))
* The opionated module sets all other MIDs to the above format

I'd probably suggest setting to a new default, but provide an option to override, meaning existing users could maintain compatibility.

**Comment by dutsmiller** [comment]
Included in v4.2.0
