### ISSUE TITLE
Example in README has default_node_pool_name, which is not a valid variable for the module.

### ISSUE THREAD

**Issue by BarnumD** [Azure-Terraform/terraform-azurerm-kubernetes#69]
Example in README has default_node_pool_name, which is not a valid variable for the module. What should this say instead?

**Comment by BarnumD** [comment]
Additionally `node_pool_subnets` is referenced, but no available.

**Comment by dutsmiller** [comment]
Good catch.  I think we'd decided to remove the example in the README but never got around to it.  The example subfolder contains code which is used to test the module and should be kept up-to-date.

https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/tree/master/example/mixed-arch
