### ISSUE TITLE
Error when attempting to output kube_config_raw

### ISSUE THREAD

**Issue by gfortil** [Azure-Terraform/terraform-azurerm-kubernetes#80]
```
Error: Output refers to sensitive values
│ 
│   on .terraform/modules/kubernetes/output.tf line 32:
│   32: output "kube_config_raw" {
│ 
│ Expressions used in outputs can only refer to sensitive values if the sensitive attribute is true.

```

should `azurerm_kubernetes_cluster.aks.kube_admin_config_raw` be assigned to a variable with a sensitive attribute before being outputted?

**Comment by fabiendelpierre** [comment]
The error suggests it's a bug/oversight in our code [here](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/master/output.tf#L32-L36). This output resource should have `sensitive = true`. At least that's what the error is saying (the `sensitive` argument is supported not only in input variables, but also in outputs).

**Comment by gfortil** [comment]
yeah, we need a sensitive attribute in this output.

**Comment by dutsmiller** [comment]
v4.2.1


https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/pull/82
