### ISSUE TITLE
Add support for azurerm 3.0

### ISSUE THREAD

**Issue by gfortil** [Azure-Terraform/terraform-azurerm-kubernetes#86]
azurerm 3.0 does not support the followings:
 Error: Unsupported argument
│
│   on .terraform/modules/kubernetes/main.tf line 54, in resource "azurerm_kubernetes_cluster" "aks":
│   54:     availability_zones           = local.node_pools[var.default_node_pool].availability_zones
│
│ An argument named "availability_zones" is not expected here.
╵
╷
│ Error: Unsupported block type
│
│   on .terraform/modules/kubernetes/main.tf line 77, in resource "azurerm_kubernetes_cluster" "aks":
│   77:   addon_profile {
│
│ Blocks of type "addon_profile" are not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on .terraform/modules/kubernetes/main.tf line 105, in resource "azurerm_kubernetes_cluster" "aks":
│  105:     user_assigned_identity_id = (var.identity_type == "SystemAssigned" ? null :
│
│ An argument named "user_assigned_identity_id" is not expected here.
╵
╷
│ Error: Unsupported block type
│
│   on .terraform/modules/kubernetes/main.tf line 111, in resource "azurerm_kubernetes_cluster" "aks":
│  111:   role_based_access_control {
│
│ Blocks of type "role_based_access_control" are not expected here.

**Comment by gfortil** [comment]
```
`addon_profile` block has been deprecated and will be removed in version 3.0 of the AzureRM Provider. All properties within the block will move to the top level.
│
│ (and 4 more similar warnings elsewhere)
```

**Comment by fabiendelpierre** [comment]
This probably won't get fixed as we're moving away from this module. Currently this module is used as a component of our internal AKS module, but this dependency is being removed in an upcoming version of the internal module, and this one will no longer be maintained. You're encouraged to move to the internal one.
