### ISSUE TITLE
FIPS 140 Node Pools 

### ISSUE THREAD

**Issue by jfivekillerln** [Azure-Terraform/terraform-azurerm-kubernetes#87]
I am investigating FIPS nodes pools for AKS, and I am wondering if you all will add support for FIPS? 

The module published on the terraform registry says it supports a fips option...

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#fips_enabled

**Comment by fabiendelpierre** [comment]
Hi John,

It should be assumed this module will not be updated anymore. Our internal module for AKS is being updated to remove the dependency on this module. If you're looking for a particular feature not currently supported, you should create an issue in the internal module's repo.

**Comment by jfivekillerln** [comment]
Thanks I will open a ticket in the AKS module
