### ISSUE TITLE
Not compatible with the latest AzureRM Provider 3.1.0

### ISSUE THREAD

**Issue by tomsri01** [Azure-Terraform/terraform-azurerm-kubernetes#88]
Seems this module is incompatible with the newer azurerm providers.
I think about 2.98.0 and upwards is broken.

**Comment by fabiendelpierre** [comment]
Hello,

It should be assumed this module will not be updated anymore. Our internal module for AKS will soon be updated to remove the dependency on this module. Please use the current version of the internal module instead.
